version: '2'
services:
  processing-service:
    container_name: processing-service
    build:
      context: processing
    image: processing-service:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
  repository-service:
    container_name: repository-service
    build:
      context: repository
    image: repository-service:latest
    ports:
      - 8081:8081
    links:
      - mongo-db
      - kafka:kafka
    depends_on:
      - kafka  
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPIC: "words.processed:1:3"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper  
